application:
  name: dbservice
  port: 8765

image: 
  name: besanouno/kdemo-dbservice
  tag: "2.4"

deployment:
  replicas: 1
  restartPolicy: Always
  resources:
    requests:
      cpu: 200m
    limits:
      cpu: 500m
