application:
  name: noteservice
  port: 8901

image: 
  name: besanouno/kdemo-noteservice
  tag: "2.4"

deployment:
  replicas: 1
  restartPolicy: Always
  resources:
    requests:
      cpu: 200m
    limits:
      cpu: 500m